server {
    listen 80;

    location /api/ {
        proxy_pass http://127.0.0.1:5000/api/;
    }

    location /r/ {
        proxy_pass http://127.0.0.1:5000/r/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
